Add Network Tier support to L4 NetLB
kubernetes/ingress-gce pull request #1636
Opened 2021-12-13 14:03 UTC by kl52752

2021-12-13 14:04 UTC, kl52752 commented
/assign @freehan @prameshj

2021-12-16 11:06 UTC, cezarygerard commented
No new tests in forwarding_rules_test.go ?
Maybe we should cover the network tier in the unit tests?

2021-12-16 11:13 UTC, kl52752 commented on pkg/loadbalancers/forwarding_rules.go
> +		addrMgr = newAddressManager(l.cloud, nm, l.cloud.Region(), subnetworkURL, loadBalancerName, ipToUse, cloud.SchemeInternal, cloud.NetworkTierPremium)
Yes,  ILB Forwarding rules can only be created in Premium tier.

2021-12-16 14:34 UTC, kl52752 commented on pkg/loadbalancers/forwarding_rules.go
> +		addrMgr = newAddressManager(l.cloud, nm, l.cloud.Region(), subnetworkURL, loadBalancerName, ipToUse, cloud.SchemeInternal, cloud.NetworkTierPremium)
I also added test cases you asked in comment above

2021-12-17 01:10 UTC, freehan commented
/ok-to-test

Need to rebase

2021-12-17 01:16 UTC, freehan commented on pkg/loadbalancers/forwarding_rules.go
> +		if err := l4netlb.tearDownResourcesWithWrongNetworkTier(existingFwdRule, ipToUse, netTier); err != nil {
There is also a project wide network tier default config in GCE API. [
](https://cloud.google.com/network-tiers/docs/using-network-service-tiers#setting_the_tier_for_all_resources_in_a_project)


I am wondering if the old NetLB created, does the service controller specify network tier during creation? If not, then it uses the project level default. Please bear in mind that some user might change the default config. Will this accidentally tear down user's old LB?

2021-12-17 01:18 UTC, freehan commented on pkg/loadbalancers/forwarding_rules.go
> +func (l4netlb *L4NetLB) tearDownResourcesWithWrongNetworkTier(existingFwdRule *composite.ForwardingRule, ipToUse string, svcNetTier cloud.NetworkTier) error {
add comment

2021-12-17 01:18 UTC, freehan commented on pkg/loadbalancers/forwarding_rules.go
> +		if err == nil && addr != nil && addr.NetworkTier != svcNetTier.ToGCEValue() {
suggest to write it this way:

addr, err := l4netlb.cloud.GetRegionAddressByIP(l4netlb.cloud.Region(), ipToUse)

if utils.IsNotFoundError(err) {
    return nil
}

....// delete and check error

2021-12-17 03:39 UTC, prameshj commented on pkg/l4netlb/l4netlbcontroller_test.go
> +	// should include network tier annotation in Service.
nit: "they" should include network tier...

2021-12-17 03:39 UTC, prameshj commented on pkg/l4netlb/l4netlbcontroller_test.go
> +	if err := lc.sync(key); err == nil {
Maybe we should test the case where a mismatch results in an expected error?

2021-12-17 03:39 UTC, prameshj commented on pkg/loadbalancers/forwarding_rules.go
> +		addrMgr = newAddressManager(l.cloud, nm, l.cloud.Region(), subnetworkURL, loadBalancerName, ipToUse, cloud.SchemeInternal, cloud.NetworkTierPremium)
Add comment above this line that ILB always Premium tier?

2021-12-17 03:39 UTC, prameshj commented on pkg/loadbalancers/forwarding_rules.go
> +	// check if it match network tiers form forwarding rule and external ip Address.
nit: s/form/from

2021-12-17 03:39 UTC, prameshj commented on pkg/loadbalancers/forwarding_rules.go
> +			if ipToUse == l4netlb.Service.Spec.LoadBalancerIP {
Why does this mean it is user-owned? Is it because GCE-reserved IPs are released immediately?Can you add a comment?

2021-12-20 00:19 UTC, Vlad1mir-D commented
This feature is so long awaited.
Thank you guys, please keep this up!

2021-12-20 09:26 UTC, kl52752 commented on pkg/loadbalancers/forwarding_rules.go
> +		if err == nil && addr != nil && addr.NetworkTier != svcNetTier.ToGCEValue() {
done

2021-12-20 09:26 UTC, kl52752 commented on pkg/loadbalancers/forwarding_rules.go
> +func (l4netlb *L4NetLB) tearDownResourcesWithWrongNetworkTier(existingFwdRule *composite.ForwardingRule, ipToUse string, svcNetTier cloud.NetworkTier) error {
done

2021-12-20 09:27 UTC, kl52752 commented on pkg/l4netlb/l4netlbcontroller_test.go
> +	// should include network tier annotation in Service.
done

2021-12-20 09:32 UTC, kl52752 commented on pkg/l4netlb/l4netlbcontroller_test.go
> +	if err := lc.sync(key); err == nil {
Well actually this is the case. I added check for error message and some comment.

2021-12-20 09:33 UTC, kl52752 commented on pkg/loadbalancers/forwarding_rules.go
> +	// check if it match network tiers form forwarding rule and external ip Address.
done

2021-12-20 09:51 UTC, kl52752 commented on pkg/loadbalancers/forwarding_rules.go
> +			if ipToUse == l4netlb.Service.Spec.LoadBalancerIP {
No. it is because if User want to create LB with specific address he needs to add it to Spec loadBalancerIP field. When Ingress-GCE creates ephemeral IP address for LB this field (loadBalancerIP) is not populated and remain empty. In the address manager the check to distinguish between User own and Controller own address is address name (for controller own address its name should match load balancer name) but since I have service here it is easier for me to check service spec.

2021-12-20 09:58 UTC, kl52752 commented on pkg/loadbalancers/forwarding_rules.go
> +			if ipToUse == l4netlb.Service.Spec.LoadBalancerIP {
Or maybe this assumption is wrong. The user can specify ip address in service spec that is not reserved then the controller will try to reserve this address and if operation is successful then this will be controller owned address?
Does it make and sense?

2021-12-20 10:28 UTC, kl52752 commented on pkg/loadbalancers/forwarding_rules.go
> +		if err := l4netlb.tearDownResourcesWithWrongNetworkTier(existingFwdRule, ipToUse, netTier); err != nil {
The old NetLB checks for service Network Tier annotation and if it is not present then it sets NT for default (Premium). https://github.dev/kubernetes/kubernetes/blob/489fb9bee3f626b3eeb120a5af89ad8c2b2f1c20/staging/src/k8s.io/legacy-cloud-providers/gce/gce_loadbalancer_external.go#L95
Then this Network Tier is passed to ensure address IP and forwarding rule.
Resources with wrong NT will only be teared down if the service annotation is present in other case there will be an error ensuring LB (but the resources will not be changed).

2021-12-21 00:51 UTC, prameshj commented on pkg/l4lb/l4netlbcontroller_test.go
> +	lc.ctx.Cloud.Compute().(*cloud.MockGCE).MockAddresses.InsertHook = test.InsertAddressErrorHook
Do you need this ErrorHook? The test needs to: 1) Create Address with standard tier 2) Sync LB and see the WrongNetworkTierError when creating forwarding rule, right?

2021-12-21 00:51 UTC, prameshj commented on pkg/loadbalancers/address_manager_test.go
> +	svc.Compute().(*cloud.MockGCE).MockAddresses.InsertHook = test.InsertAddressErrorHook
Same question as my other comment - why do we need this Error hook? Even without this, HoldAddress() should invoke validateAddress that will throw the mismatched tier error?

2021-12-21 00:51 UTC, prameshj commented on pkg/loadbalancers/forwarding_rules.go
> +			if ipToUse == l4netlb.Service.Spec.LoadBalancerIP {
`l4netlb.Service.Spec.LoadBalancerIP != ""` does not guarantee that user reserved the ip. As you mentioned, user can specify an IP(without reserving) and expect the controller to reserve it.
Also, when service Update is processed, or if the controller restarts due to master upgrade, it will get a service object with LoadBalancer IP populated. That does not mean it is user-reserved.

However, addr != nil means user reserved it, right?

2021-12-21 00:51 UTC, prameshj commented on pkg/loadbalancers/forwarding_rules.go
> +		if err := l4netlb.tearDownResourcesWithWrongNetworkTier(existingFwdRule, ipToUse, netTier); err != nil {
@freehan What do we expect to happen in case user changed the project-wide default. Example - 1) Default was premium, they created NetLB and reserved IP in premium tier.
2) They changed project default to Standard.  They did not change the tier for the address.
3) GetNetworkTier in controller still picks premium as default(since it is a const string). So no errors in LB sync loop.
But future NetLBs that don't specify any tier annotation, will also be created in premium default. Their project-wide setting wont be applied. This should be ok?

2021-12-21 07:43 UTC, kl52752 commented on pkg/loadbalancers/forwarding_rules.go
> +			if ipToUse == l4netlb.Service.Spec.LoadBalancerIP {
`However, addr != nil means user reserved it, right?` no this might means that this is Update operation and address was reserved by controller previously. Well I think I need to check address name as it is in address manager.

2021-12-21 08:08 UTC, kl52752 commented on pkg/l4lb/l4netlbcontroller_test.go
> +	lc.ctx.Cloud.Compute().(*cloud.MockGCE).MockAddresses.InsertHook = test.InsertAddressErrorHook
Yes you are right this mock is not necessary here

2021-12-21 08:13 UTC, kl52752 commented on pkg/loadbalancers/forwarding_rules.go
> +		addrMgr = newAddressManager(l.cloud, nm, l.cloud.Region(), subnetworkURL, loadBalancerName, ipToUse, cloud.SchemeInternal, cloud.NetworkTierPremium)
done

2021-12-21 09:01 UTC, kl52752 commented on pkg/loadbalancers/address_manager_test.go
> +	svc.Compute().(*cloud.MockGCE).MockAddresses.InsertHook = test.InsertAddressErrorHook
removed

2021-12-22 15:41 UTC, prameshj commented
Couple of nits, otherwise LGTM.

2021-12-29 00:19 UTC, freehan commented on pkg/utils/utils.go
> +		fallthrough
why is this fallthrough?

2021-12-29 00:23 UTC, freehan requested changes

2021-12-29 00:23 UTC, freehan commented on pkg/loadbalancers/forwarding_rules.go
> +		if isFromSvc {
This means the GCE project wide default will be effective right? I thought we decided to ignore the project level default and treat the annotation as source of truth. If the annotation is not present, then use Premium tier.

2021-12-29 00:23 UTC, freehan commented on pkg/annotations/service.go
> +	NetworkTierAnnotationKey = "cloud.google.com/network-tier"
// The valid values are "Standard" and "Premium" (default, if unspecified).

2021-12-29 00:23 UTC, freehan commented
Need rebase as well

2021-12-29 00:32 UTC, freehan commented on pkg/loadbalancers/forwarding_rules.go
> +		if isFromSvc {
If the existing service controller supports the GCE project wide default, then we should be backward compatible. Can you double check?

2021-12-29 08:03 UTC, kl52752 commented on pkg/utils/utils.go
> +		fallthrough
changed.

2021-12-29 08:07 UTC, kl52752 commented on pkg/loadbalancers/forwarding_rules.go
> +		if isFromSvc {
Yes, you are right project level network tier is ignored here.
`isFromSvc ` means that annotation is present in service spec and according to svc controllers codebase we should tear down resources`only when` annotation is present in service. Maybe the name is wrong I can rename it to `isFromAnnotation`?

2021-12-29 08:09 UTC, kl52752 commented on pkg/annotations/service.go
> +	NetworkTierAnnotationKey = "cloud.google.com/network-tier"
done

2021-12-30 22:49 UTC, freehan approved these changes
/lgtm
/approve

2022-01-03 12:18 UTC, kl52752 commented
@freehan @prameshj I found some bug related to ILB we cannot create internal IP address and set Network Tier (even for Premium). I fixed it and added UT.

2022-01-07 01:13 UTC, freehan commented
/lgtm
/approve

2022-01-07 01:14 UTC, merged