Multiple instance group management #1
kubernetes/ingress-gce pull request #1657
Opened 2022-01-25 15:35 UTC by cezarygerard

This part creates new implementation of NodePool interface that can handle multiple Instance Groups in existing controllers

The "enable-multiple-igs" flag keeps new logic disabled.

2022-01-25 18:48 UTC, freehan commented
/ok-to-test

2022-01-26 14:00 UTC, kl52752 requested changes

2022-01-26 14:00 UTC, kl52752 commented on pkg/backends/regional_ig_linker.go
> +	linker.instancePool.List()
Well, I guess that it will be used to link igs but now it's unused and can be removed

2022-01-26 14:00 UTC, kl52752 commented on pkg/flags/flags.go
> +	flag.BoolVar(&F.EnableMultipleIGs, "enable-multiple-igs", false, "Enable using unmanaged instance group management")
```suggestion
	flag.BoolVar(&F.EnableMultipleIGs, "enable-multiple-igs", false, "Enable using multi instance group management")
```

2022-01-26 14:00 UTC, kl52752 commented on pkg/instancegroup/multi_ig_node_controller.go
> +Copyright 2015 The Kubernetes Authors.
```suggestion
Copyright 2022 The Kubernetes Authors.
```

2022-01-26 14:00 UTC, kl52752 commented on pkg/instancegroup/multi_ig_node_controller.go
> +func NewMultiInstancesGroupController(ctx *context.ControllerContext, stopCh chan struct{}) *MultiIGNodeController {
```suggestion
func NewMultiInstancesGroupController(ctx *context.ControllerContext, stopCh <-chan struct{}) *MultiIGNodeController {
```

2022-01-26 14:00 UTC, kl52752 commented on pkg/instancegroup/multi_ig_node_controller.go
> +	igc.queue.Shutdown()
I think this line is unnecessary, I would just type it into line number 83

2022-01-26 14:00 UTC, kl52752 commented on pkg/instances/multi_ig_instances.go
> +Copyright 2015 The Kubernetes Authors.
```suggestion
Copyright 2022 The Kubernetes Authors.
```

2022-01-26 14:00 UTC, kl52752 commented on pkg/instances/multi_ig_instances.go
> +			instanceLinkFormat: basePath + "zones/%s/instances/%s",
can we move this `basePath + "zones/%s/instances/%s"` to a function since it is used in 2 places now?

2022-01-26 14:00 UTC, kl52752 commented on pkg/instances/multi_ig_instances.go
> +	klog.Infof("Sync is a no-op. Instance groups will be synced in the separate controller.")
```suggestion
	klog.Infof("Sync is a no-op. Instance groups will be synced in the multi instance group controller.")
```

2022-01-26 14:00 UTC, kl52752 commented on pkg/instances/multi_ig_instances.go
> +func (igc *MultiIGInstances) Get(name, zone string) ([]*compute.InstanceGroup, error) {
Add comment

2022-01-26 14:00 UTC, kl52752 commented on pkg/instances/multi_ig_instances.go
> +func (igc *MultiIGInstances) EnsureInstanceGroupsAndPorts(name string, ports []int64) (igs []*compute.InstanceGroup, err error) {
Add comment

2022-01-26 14:00 UTC, kl52752 commented on pkg/instances/multi_ig_instances.go
> +
delete

2022-01-26 14:00 UTC, kl52752 commented on pkg/instances/multi_ig_instances.go
> +		ig, err := igc.Get(name, zone)
Your variable is ig but Get method returns a list so it is confusing. I think you should rename one of this variable  
ig -> zoneIGs or igs -> allIGs ?

2022-01-26 14:00 UTC, kl52752 commented on pkg/instances/multi_ig_instances_test.go
> +package instances
Add header

2022-01-26 14:00 UTC, kl52752 commented on pkg/instances/multi_ig_instances_test.go
> +			result, err := multiIGInst.Get(igName, "zone1")
```suggestion
			result, err := multiIGInst.Get(igName, zone)
```
this is already a const

2022-01-26 14:00 UTC, kl52752 commented on pkg/instances/multi_ig_instances_test.go
> +				t.Errorf("Unexpected error, got: %v, want no error", err)
I think that this comment is wrong because with case when we don't want the error then we will receive it we will fail. (and this is good just message is wrong :))

2022-01-26 14:00 UTC, kl52752 commented on pkg/instances/multi_ig_instances_test.go
> +	zones := []string{"zone1"}
```suggestion
	zones := []string{zone}
```

2022-01-26 14:00 UTC, kl52752 commented on pkg/utils/namer/namer.go
> +		(strings.HasPrefix(fullClusterName, componentClusterName) || strings.HasPrefix(componentClusterName, fullClusterName))
can you explain this change?

2022-01-26 17:06 UTC, cezarygerard commented on pkg/utils/namer/namer.go
> +		(strings.HasPrefix(fullClusterName, componentClusterName) || strings.HasPrefix(componentClusterName, fullClusterName))
please take a look at new test cases in
pkg/utils/namer/namer_test.go
in func TestNameBelongsToCluster

ig names stripped to 'componentClusterName' contains fullClusterName
So this change is meant for namer pick up instance groups with suffixes: "-1",  "-11"  etc

2022-01-26 17:08 UTC, cezarygerard commented on pkg/backends/regional_ig_linker.go
> +	linker.instancePool.List()
yes.

2022-01-26 17:11 UTC, cezarygerard commented on pkg/instances/multi_ig_instances_test.go
> +				t.Errorf("Unexpected error, got: %v, want no error", err)
fixed

2022-01-26 18:23 UTC, cezarygerard commented
/retest

2022-01-26 23:59 UTC, freehan commented on pkg/instances/interfaces.go
> -	Add(groupName string, nodeNames []string) error
If you removed the Add/Remove interface, you should remove the implementation as well.

2022-01-26 23:59 UTC, freehan commented on pkg/instancegroup/multi_ig_node_controller.go
> +			igc.queue.Enqueue(newObj)
you need to filter out kubelet heartbeat. This will be a problem at scale.

2022-01-26 23:59 UTC, freehan commented on pkg/instances/instances.go
> +func (i *Instances) setPorts(igs []*compute.InstanceGroup, name, zone string, ports []int64) error {
nit: comment

2022-01-26 23:59 UTC, freehan commented on pkg/instances/multi_ig_instances.go
> +type MultiIGInstances struct {
add comment: MultiIGInstances implements the NodePool Interface etc.

2022-01-26 23:59 UTC, freehan commented on pkg/utils/namer/namer.go
> +		(strings.HasPrefix(fullClusterName, componentClusterName) || strings.HasPrefix(componentClusterName, fullClusterName))
Can you update the above comments to include your example?

2022-01-27 10:36 UTC, cezarygerard commented on pkg/instances/interfaces.go
> -	Add(groupName string, nodeNames []string) error
functions Add/Remove are used only inside the instances.go
changed to unexported add/remove

2022-01-27 15:42 UTC, cezarygerard commented on pkg/instances/multi_ig_instances.go
> +type MultiIGInstances struct {
done

2022-01-27 19:08 UTC, cezarygerard commented
@freehan applied all the comments

2022-01-31 11:18 UTC, panslava requested changes

2022-01-31 11:19 UTC, panslava commented on pkg/instancegroup/multi_ig_node_controller.go
> +func NewMultiInstancesGroupController(ctx *context.ControllerContext, stopCh <-chan struct{}) *MultiIGNodeController {
maybe rename to `NewMultiIGNodeController`

2022-01-31 11:25 UTC, panslava commented on pkg/instances/multi_ig_instances.go
> +type MultiIGInstances struct {
I can be wrong, but what do you think if we rename it to `MultiIGNodePool`

Because legacy one is called `NodePool`, and it would be more consistent and easier to understand if we follow the same pattern

2022-02-01 13:10 UTC, cezarygerard commented on cmd/glbc/main.go
> +		igController := instancegroup.NewMultiInstancesGroupController(ctx, stopCh)
Done

2022-02-01 13:10 UTC, cezarygerard commented on pkg/instancegroup/multi_ig_node_controller.go
> +func NewMultiInstancesGroupController(ctx *context.ControllerContext, stopCh <-chan struct{}) *MultiIGNodeController {
Done

2022-02-02 14:16 UTC, cezarygerard commented
Rebased and squashed commits.

2022-02-02 15:36 UTC, kl52752 requested changes

2022-02-02 15:36 UTC, kl52752 commented on pkg/instancegroup/multi_ig_node_controller.go
> +			if utils.NodeStatusChanged(oldObj.(*apiv1.Node), newObj.(*apiv1.Node)) {
@freehan With new design we need periodic sync to ensure Instance Groups are created because Services and Ingresses will not create IGs on demand (Controller is the only place where IGs are created and sync with instances). Ingress-gce does not delete IGs (they will be deleted during cluster deletion) but if User or other controller deletes IGs then they will be ensure only in case a node will be added/updated/deleted and it might take too long. 
If kubelet heartbeat happens too often then maybe we can consider fg creating new Goroutine which will ensure that IGs are created and its period might be longer.

2022-02-02 21:01 UTC, cezarygerard commented on pkg/instancegroup/multi_ig_node_controller.go
> +			if utils.NodeStatusChanged(oldObj.(*apiv1.Node), newObj.(*apiv1.Node)) {
The sync func will have to list all the nodes anyway

Maybe we should simply make sure the syn happens at least every 5-10 minutes?


```
	ctx.NodeInformer.AddEventHandler(cache.ResourceEventHandlerFuncs{
		AddFunc: func(obj interface{}) {
			igc.queue.Enqueue(obj)
			igc.lastIGSync = time.Now()
		},
		DeleteFunc: func(obj interface{}) {
			igc.queue.Enqueue(obj)
			igc.lastIGSync = time.Now()
		},
		UpdateFunc: func(oldObj, newObj interface{}) {
			if time.Since(igc.lastIGSync) > 5 *time.Minute {
				igc.lastIGSync = time.Now()
				igc.queue.Enqueue(newObj)
			}
		},
	})
```

where the 5 *time.Minute should be configurable via the flag

2022-02-03 16:20 UTC, cezarygerard commented on pkg/instancegroup/multi_ig_node_controller.go
> +			if utils.NodeStatusChanged(oldObj.(*apiv1.Node), newObj.(*apiv1.Node)) {
@freehan  @kl52752 
I have left the TODO, to implement the periodic sync for instance groups.
I want this PR to be merged soon, no to block Slavik on Instance Group sync algorithm.

2022-02-04 08:34 UTC, kl52752 commented on pkg/instancegroup/multi_ig_node_controller.go
> +			if utils.NodeStatusChanged(oldObj.(*apiv1.Node), newObj.(*apiv1.Node)) {
SGTM

2022-02-08 14:15 UTC, cezarygerard commented
@freehan 
gentle ping

2022-02-08 23:53 UTC, cezarygerard commented
/assign @bowei

2022-11-26 01:22 UTC, closed without merging