Add check for forwarding rule name in annotation for l4 rbs
kubernetes/ingress-gce pull request #1666
Opened 2022-02-02 14:11 UTC by panslava

2022-02-02 14:50 UTC, panslava commented
/assign @bowei

2022-02-02 14:54 UTC, kl52752 requested changes

2022-02-02 14:54 UTC, kl52752 commented on pkg/l4lb/l4netlbcontroller_test.go
> +			desc:         "Should detect RBS by TCP forwarding rule annotation with matching name",
```suggestion
			desc:         "Should detect RBS by UDP forwarding rule annotation with matching name",
```

2022-02-02 14:54 UTC, kl52752 commented on pkg/l4lb/l4netlbcontroller_test.go
> +				ilbSvc := test.NewL4ILBService(false, 8080)
I think that you should add here TCP/UDP annotation with ilb naming scheme.

2022-02-03 11:33 UTC, panslava commented on pkg/l4lb/l4netlbcontroller_test.go
> +			desc:         "Should detect RBS by TCP forwarding rule annotation with matching name",
Thank you, fixed

2022-02-03 11:33 UTC, panslava commented on pkg/l4lb/l4netlbcontroller_test.go
> +				ilbSvc := test.NewL4ILBService(false, 8080)
Thank you, added!

2022-02-03 11:34 UTC, panslava commented
/assign @freehan

2022-02-03 21:10 UTC, cezarygerard commented on pkg/l4lb/l4netlbcontroller_test.go
> +		{
there is so many things that could be improved with this TestIsRBSBasedService
- use simple test struct outside of for loop (such approach has IDE support)
- keep the test case struct simple
- build the required structs inside the for loop
- limit anonymous functions calls
- you don't have to run all tests for a faeture in single loop, just run those with similar setup
- use 	t.Run(testCase.desc, func(t *testing.T) so test frameworks can see different test cases
- format test error messages with got before want

Check the refactore version here: https://github.com/kubernetes/ingress-gce/pull/1669


For testing the forwarding rule annotation you can use simple, non-table test:

```
func TestForwardingRuleAnnotations(t *testing.T) {
	svc := test.NewL4LegacyNetLBService(8080, 30234)
	controller := newL4NetLBServiceController()
	l4netlb := loadbalancers.NewL4NetLB(svc, controller.ctx.Cloud, meta.Regional, controller.namer, controller.ctx.Recorder(svc.Namespace), &controller.sharedResourcesLock)
	frName := l4netlb.GetFRName()

	// just make sure the APi is not called once
	controller.ctx.Cloud.Compute().(*cloud.MockGCE).MockForwardingRules.GetHook = func (ctx context.Context, key *meta.Key, m *cloud.MockForwardingRules) (bool, *ga.ForwardingRule, error) {
		t.Errorf("this should not be called")
		return true, nil, nil
	}
	expectRBSService := true

	svc.Annotations = map[string]string{annotations.TCPForwardingRuleKey: frName}
	if expectRBSService != controller.isRBSBasedService(svc) {
		t.Errorf("Should detect RBS by TCP forwarding rule annotation. isRBSBasedService(%v) = %v, want %v", svc, false, expectRBSService)
	}

	svc.Annotations = map[string]string{annotations.UDPForwardingRuleKey: frName}
	if expectRBSService != controller.isRBSBasedService(svc) {
		t.Errorf("Should detect RBS by UDP forwarding rule annotation. isRBSBasedService(%v) = %v, want %v", svc, false, expectRBSService)
	}
}
```

plus add one test case into my refactoring from pull/1669

```
		{
			desc:         "Should not detect RBS by forwarding rule annotations without matching name",
			annotations : map[string]string{annotations.UDPForwardingRuleKey: "fr-1", annotations.TCPForwardingRuleKey: "fr-2"},
			expectRBSService: false,
		},
```

2022-02-04 17:12 UTC, panslava commented on pkg/l4lb/l4netlbcontroller_test.go
> +		{
thank you, fixed

2022-02-04 17:22 UTC, kl52752 commented on pkg/l4lb/l4netlbcontroller_test.go
> +			desc:             "Should detect RBS by finalizer when service contains legacy finalizer",
```suggestion
			desc:             "Should detect RBS by finalizer when service contains both legacy and NetLB finalizers",
```

2022-02-04 17:26 UTC, cezarygerard commented
/lgtm

2022-02-07 09:51 UTC, kl52752 commented
/lgtm

2022-02-08 14:16 UTC, cezarygerard commented
@bowei @freehan

as for now this is the top priority PR for RBS
 we need this to enable RBS controller on nightly tests

2022-02-08 17:45 UTC, swetharepakula commented
/ok-to-test

2022-02-15 00:49 UTC, freehan approved these changes
/lgtm
/approve

2022-02-15 00:52 UTC, merged