Do not restart controller after L4 healthcheck failure, publish metrics instead
kubernetes/ingress-gce pull request #1694
Opened 2022-04-11 14:26 UTC by cezarygerard

Do not restart controller after L4 healthcheck failure, publish metrics instead

After discussion offline we decide that restarting controller on single healthckeck failure may be too invasive and reduce the reliability. 

This PR undoes the https://github.com/kubernetes/ingress-gce/pull/1683 and replaces healthcheck failure error with metric to count the errors.

2022-04-12 07:43 UTC, cezarygerard commented
/assign @freehan @bowei @swetharepakula

2022-04-12 10:32 UTC, kl52752 commented on pkg/l4lb/metrics/metrics.go
> +func PublishLL4FailedHealthCheckCount(controllerName string) {
Why double L? maybe it should be `PublishL4FailedHealthCheckCount`

2022-04-12 11:26 UTC, panslava requested changes

2022-04-12 11:26 UTC, panslava commented on pkg/l4lb/metrics/metrics.go
> +	klog.V(3).Infof("Registering L4  healthcheck failures count metric: %v", l4FailedHealthCheckCount)
remove double space after `Registering L4`

2022-04-12 23:49 UTC, freehan approved these changes
/lgtm
/approve

2022-04-12 23:50 UTC, freehan commented
/ok-to-test

2022-04-13 09:21 UTC, cezarygerard commented on pkg/l4lb/metrics/metrics.go
> +	klog.V(3).Infof("Registering L4  healthcheck failures count metric: %v", l4FailedHealthCheckCount)
fixed, thanks!

2022-04-13 09:22 UTC, cezarygerard commented on pkg/l4lb/l4controller.go
> +	l4ILBLBControllerName       = "l4-ilb-subsetting-controller"
fixed, thanks!

2022-04-13 09:22 UTC, cezarygerard commented
@freehan 
all the nits are fixed

2022-04-13 23:45 UTC, freehan commented
/lgtm
/approve

2022-04-13 23:46 UTC, merged