add label user error
kubernetes/ingress-gce pull request #1698
Opened 2022-04-14 15:16 UTC by kl52752

2022-04-14 15:22 UTC, kl52752 commented
/assign @bowei 
/assign @freehan

2022-04-14 16:23 UTC, cezarygerard commented on pkg/test/gcehooks.go
> +	fwRule := compute.ForwardingRule{BackendService: bsUrl, LoadBalancingScheme: string(cloud.SchemeExternal), NetworkTier: cloud.NetworkTierStandard.ToGCEValue()}
not needed, put a dummy string "some_standard_tier_bs"

2022-04-14 16:23 UTC, cezarygerard commented on pkg/utils/utils.go
> +	var re = regexp.MustCompile(`The network tier of external IP is STANDARD|PREMIUM, that of Address must be the same.`)
can you unit test this func isNetworkMismatchGCEError?


maybe it would be better to have some more lenient check
just 
"The network tier of "
PLUS

"Address must be the same"

2022-04-14 16:23 UTC, cezarygerard commented on pkg/metrics/metrics.go
> +			// Skip counting other features if the service is in error state.
// Skip counting other features if the service is in user-caused error state.

2022-04-14 18:55 UTC, kl52752 commented on pkg/test/gcehooks.go
> +	fwRule := compute.ForwardingRule{BackendService: bsUrl, LoadBalancingScheme: string(cloud.SchemeExternal), NetworkTier: cloud.NetworkTierStandard.ToGCEValue()}
actaully no we need whole url for forwarding rule compression https://github.dev/kubernetes/ingress-gce/blob/cc2910140315638c2da19dca3e9ea5e8f6746d00/pkg/loadbalancers/forwarding_rules.go#L450

2022-04-14 19:06 UTC, kl52752 commented on pkg/utils/utils.go
> +	var re = regexp.MustCompile(`The network tier of external IP is STANDARD|PREMIUM, that of Address must be the same.`)
added UT

2022-04-14 19:06 UTC, kl52752 commented on pkg/metrics/metrics.go
> +			// Skip counting other features if the service is in error state.
done

2022-04-15 03:57 UTC, freehan commented on pkg/l4lb/l4netlbcontroller_test.go
> +	return err != nil && strings.Contains(err.Error(), "network tier mismatch")
consider switching to use the error wrapping/unwrapping mechanism to evaluate error types?

https://golangbyexample.com/wrapping-and-unwrapping-error-golang/#Unwrap_an_error

2022-04-15 03:57 UTC, freehan commented on pkg/utils/utils.go
> +	var re = regexp.MustCompile(`The network tier of external IP is STANDARD|PREMIUM, that of Address must be the same.`)
I am curious if there is a GCE error type specific for this in the GCE go client?

2022-04-15 03:57 UTC, freehan commented on pkg/loadbalancers/address_manager.go
> +	} else if utils.IsNetworkTierError(reserveErr) {
move this section to below line 151. 
Consider something like this
```
const ErrNetTierMismatch = fmt.Errorf("Address network tier mismatch")


if reserveErr != nil {
     return "", IPAddrUndefined, fmt.Errorf("Expect network tier = %s, %w", am.networkTier, ErrNetTierMismatch)
}
```

2022-04-15 03:57 UTC, freehan commented on pkg/loadbalancers/l4netlb.go
> +		result.MetricsState.IsUserError = utils.IsNetworkTierError(err)
I would suggest have a function to evaluate error 
```
func IsUserError(err Error) bool {
   if utils.IsNetworkTierError(err) {
       return true
   }
   return false
}
```

2022-04-15 11:06 UTC, kl52752 commented on pkg/loadbalancers/address_manager.go
> +	} else if utils.IsNetworkTierError(reserveErr) {
actually all errors are validated below so this else is just not necessary.

2022-04-15 11:25 UTC, kl52752 commented on pkg/loadbalancers/l4netlb.go
> +		result.MetricsState.IsUserError = utils.IsNetworkTierError(err)
done

2022-04-15 11:25 UTC, kl52752 commented on pkg/l4lb/l4netlbcontroller_test.go
> +	return err != nil && strings.Contains(err.Error(), "network tier mismatch")
done, or at least I tried to :)

2022-04-20 10:56 UTC, cezarygerard commented on pkg/utils/utils.go
> +func IsNetworkTierMismatchGCEError(err error) bool {
make this func return false if err == nil

2022-04-20 10:56 UTC, cezarygerard commented on pkg/utils/utils.go
> +func IsNetworkTierError(err error) bool {
make this func return false if err == nil

this will simplify such expressions in your tests:

 if result.Error == nil || !utils.IsNetworkTierError(result.Error)

2022-04-20 11:16 UTC, kl52752 commented on pkg/utils/utils.go
> +func IsNetworkTierMismatchGCEError(err error) bool {
I don't like this idea the controller always checks if returned error is not nil then we checks specific errors if needed. Returning error here will only simplified test code but in controller there will be a duplication.

2022-04-20 11:16 UTC, kl52752 commented on pkg/utils/utils.go
> +func IsNetworkTierError(err error) bool {
I don't like this idea the controller always checks if returned error is not nil then we checks specific errors if needed. Returning error here will only simplified test code but in controller there will be a duplication.

2022-04-21 15:25 UTC, bowei commented
/ok-to-test

2022-04-26 22:35 UTC, bowei commented
Can we fix the commit message to have enough context to understand the change etc.

2022-04-26 22:43 UTC, bowei commented on pkg/utils/utils.go
> +	netTierError := errors.Unwrap(err)
We should use `errors.As(..)` to unwrap errors. This code assumes that there is only one level of wrapping for the error?

2022-04-26 22:47 UTC, bowei commented on pkg/utils/utils_test.go
> +		expected bool
[minor] expected => want

2022-04-26 22:48 UTC, bowei commented on pkg/utils/utils_test.go
> +			t.Errorf("isNetworkMismatchGCEError for error %s should return %v", tc.err.Error(), tc.expected)
if got := IsNetworkTierMismatchGCEError(tc.err); got != tc.want {
  t.Errorf("IsNetworkTierMismatchGCEError(%v) = %v, want %v", tc.err, got, tc.want)
}

2022-04-26 22:48 UTC, bowei commented on pkg/utils/utils_test.go
> +		expected bool
expected => want

2022-04-26 22:50 UTC, bowei commented on pkg/utils/utils_test.go
> +			t.Errorf("isNetworkMismatchGCEError for error %s should return %v", tc.err.Error(), tc.expected)
See above:

```
if got := ...; got != tc.want {
  ...
}
```

2022-04-26 22:58 UTC, bowei commented on pkg/test/gcehooks.go
> +	bsUrl       = "https://www.googleapis.com/compute/v1/projects/test-project/regions/us-central1/backendServices/k8s2-axyqjz2d-default-netbtest-hgray14h"
should document this -- is the string significant or just a random string.

2022-04-26 23:39 UTC, bowei commented on pkg/loadbalancers/address_manager.go
> +		wrongNetworkTierEWrror := fmt.Errorf("network tier mismatch err:%w", reserveErr)
space between err: %w

2022-04-26 23:51 UTC, bowei commented on pkg/loadbalancers/address_manager.go
> +		return "", IPAddrUndefined, fmt.Errorf("failed to reserve address %q in Network Tier %s, err: %w", am.name, am.networkTier, wrongNetworkTierEWrror)
Seems like overkill to wrap an error twice?

2022-04-26 23:51 UTC, bowei commented on pkg/loadbalancers/address_manager.go
> +			return fmt.Errorf("Error tearing down the User specific address IP (%v) err: %w", am.networkTier, networkTierMismatchError)
Do we need to wrap errors twice?

2022-04-26 23:51 UTC, bowei commented on pkg/loadbalancers/address_manager_test.go
> +		t.Fatalf("Hold Address should return Network Tier Mismatch error")
mgr.HoldAddress() = %v, utils.IsNetworkTierError(err)  = %t, want %t

is this test supposed to pass if err == nil?

2022-04-26 23:51 UTC, bowei commented on pkg/loadbalancers/forwarding_rules.go
> +			networkTierError := fmt.Errorf("%s, old: %s, new: %s", utils.NetworkTierMismatchStr, existingFwdRule.NetworkTier, fr.NetworkTier)
Double wrapped error.

Why not 

err := fmt.Errorf("...")
return nil, err

2022-04-26 23:51 UTC, bowei commented on pkg/loadbalancers/l4netlb_test.go
> +	managedIP      = true
I find this stylistically quite confusing.
There is nothing to prevent accidentally using managedIP in place of premiumTier.

Can we just document at the func call site instead of using these constants?

e.g. 

```
if err := checkMetrics(..., /*managedIP*/=true, ...)
```

2022-04-26 23:51 UTC, bowei commented on pkg/utils/utils.go
> +	var re = regexp.MustCompile(`The network tier of external IP is STANDARD|PREMIUM, that of Address must be the same.`)
If we are doing MustCompile -- I recommend initializing it in `init()` so the compilation failure will be detected immediately

2022-04-27 16:46 UTC, kl52752 commented on pkg/loadbalancers/address_manager_test.go
> +		t.Fatalf("Hold Address should return Network Tier Mismatch error")
No, this test checks that error was returned and this is NetworkTierError.
Error msg fixed

2022-04-27 16:49 UTC, kl52752 commented on pkg/loadbalancers/forwarding_rules.go
> +			networkTierError := fmt.Errorf("%s, old: %s, new: %s", utils.NetworkTierMismatchStr, existingFwdRule.NetworkTier, fr.NetworkTier)
because I wanted to include which resource returned the "NetworkTierError".
changed.

2022-04-27 16:50 UTC, kl52752 commented on pkg/loadbalancers/l4netlb_test.go
> +	managedIP      = true
changed

2022-04-29 08:49 UTC, kl52752 commented on pkg/utils/utils.go
> +	var re = regexp.MustCompile(`The network tier of external IP is STANDARD|PREMIUM, that of Address must be the same.`)
done

2022-04-29 12:37 UTC, kl52752 commented on pkg/utils/utils.go
> +	netTierError := errors.Unwrap(err)
done

2022-04-29 12:37 UTC, kl52752 commented on pkg/utils/utils_test.go
> +		expected bool
done

2022-04-29 12:39 UTC, kl52752 commented on pkg/utils/utils_test.go
> +			t.Errorf("isNetworkMismatchGCEError for error %s should return %v", tc.err.Error(), tc.expected)
done

2022-04-29 12:40 UTC, kl52752 commented on pkg/utils/utils_test.go
> +			t.Errorf("isNetworkMismatchGCEError for error %s should return %v", tc.err.Error(), tc.expected)
done

2022-04-29 12:42 UTC, kl52752 commented on pkg/test/gcehooks.go
> +	bsUrl       = "https://www.googleapis.com/compute/v1/projects/test-project/regions/us-central1/backendServices/k8s2-axyqjz2d-default-netbtest-hgray14h"
this is a significant url, was craeted based on project and region set in test. We need whole url for forwarding rule validation.

2022-04-29 12:45 UTC, kl52752 commented on pkg/loadbalancers/address_manager.go
> +		wrongNetworkTierEWrror := fmt.Errorf("network tier mismatch err:%w", reserveErr)
obsolete, done

2022-04-29 12:45 UTC, kl52752 commented on pkg/loadbalancers/address_manager.go
> +			return fmt.Errorf("Error tearing down the User specific address IP (%v) err: %w", am.networkTier, networkTierMismatchError)
fixed

2022-05-09 09:26 UTC, kl52752 commented on pkg/loadbalancers/forwarding_rules.go
> +			networkTierError := fmt.Errorf("%s, old: %s, new: %s", utils.NetworkTierMismatchStr, existingFwdRule.NetworkTier, fr.NetworkTier)
done

2022-05-09 09:26 UTC, kl52752 commented on pkg/loadbalancers/address_manager_test.go
> +		t.Fatalf("Hold Address should return Network Tier Mismatch error")
done

2022-05-09 09:26 UTC, kl52752 commented on pkg/test/gcehooks.go
> +	bsUrl       = "https://www.googleapis.com/compute/v1/projects/test-project/regions/us-central1/backendServices/k8s2-axyqjz2d-default-netbtest-hgray14h"
done

2022-05-09 22:56 UTC, panslava requested changes

2022-05-09 22:56 UTC, panslava commented on pkg/loadbalancers/address_manager.go
> +			// This is just for error message.
Sorry, I do not finally get was this code is doing...
So if `am.networkTier == cloud.NetworkTierPremium` we change  `receivedNetworkTier` to standard, but is not address manager only used for premium tier? 

(also small thing, but should be "we try")

2022-05-09 22:56 UTC, panslava commented on pkg/loadbalancers/address_manager.go
> +		return "", IPAddrUndefined, fmt.Errorf("address (%q) validation fails err: %w", addr.Name, err)
sorry for nitpicking, but probably something like `address (%q) validation failed, err: %w` would be better to understand

2022-05-09 22:56 UTC, panslava commented on pkg/loadbalancers/address_manager.go
> +		return fmt.Errorf("IP mismatch expected %q, actual: %q", am.targetIP, addr.Address)
sorry for nitpicking, 
but probably would be better to add comma
`IP mismatch, expected %q, actual: %q`

2022-05-09 22:56 UTC, panslava commented on pkg/loadbalancers/address_manager.go
> +		return fmt.Errorf("address type mismatch expected %q, actual: %q", am.addressType, addr.AddressType)
sorry for nitpicking,
but probably would be better to add comma
`address type mismatch, expected %q, actual: %q`

2022-05-09 22:56 UTC, panslava commented on pkg/loadbalancers/address_manager.go
> +			return networkTierMismatchError
I can be wrong with this, but I have a feeling, that writing this in one line makes it actually easier to read, cause you immediately understand that we just return error
however, it is long line... so discussible

```
return utils.NewNetworkTierErr(fmt.Sprintf("User specific address IP (%v)", am.name), string(am.networkTier), addr.NetworkTier)
```

2022-05-09 22:56 UTC, panslava commented on pkg/loadbalancers/address_manager.go
> +		return utils.NewNetworkTierErr(resource, am.networkTier.ToGCEValue(), addr.NetworkTier)
I can be wrong with this, but I have a feeling, that writing this in one line makes it actually easier to read, cause you immediately understand that we just return error
however, it is long line... so discussible

```
return utils.NewNetworkTierErr(fmt.Sprintf("Static IP (%v)", am.name), string(am.networkTier), addr.NetworkTier)
```

2022-05-09 22:56 UTC, panslava commented on pkg/loadbalancers/l4netlb.go
> +		// User can misconfigure the forwarding rule if Network Tier will not match desired.
Can you add a bit of clarification in this comment about "will not match desired ... what"

2022-05-09 22:56 UTC, panslava commented on pkg/utils/utils.go
> +}
I understand, Bowei commented about this, and asked to put into init(), but is there any benefit to do it in init, instead of just call regexp.MustCompile on global level?

Something like

```var re = regexp.MustCompile(`The network tier of external IP is STANDARD|PREMIUM, that of Address must be the same.`)```

2022-05-09 22:56 UTC, panslava commented on pkg/utils/utils.go
> +// Error function print out Network Tier error.
[nitpicking] 
should be `prints`

2022-05-09 22:56 UTC, panslava commented on pkg/utils/utils.go
> +	// return strings.Contains(netTierError.Error(), NetworkTierMismatchStr)
should these comments be removed?

2022-05-10 06:49 UTC, kl52752 commented on pkg/loadbalancers/address_manager.go
> +			// This is just for error message.
This is just for logging purposes. The thing is that we tried to reserve an ephemeral IP address but this action returned an error that Network Tier mismatch. We do not get the address before this action so we don't know what the actual Network Tier is. What we know is that we tried to reserve the address with Desired (standard or premium) Network Tier. So if we want to log that Network Tier mismatch and print it like `actual: %v != desired %v` we need to set actual to the opposite one we chose to reserve address in since there was a mismatch. I know that this is a bit mixed up but it is only for logging purposes.

2022-05-10 07:06 UTC, kl52752 commented on pkg/loadbalancers/address_manager.go
> +		return "", IPAddrUndefined, fmt.Errorf("address (%q) validation fails err: %w", addr.Name, err)
done

2022-05-10 07:06 UTC, kl52752 commented on pkg/loadbalancers/address_manager.go
> +		return fmt.Errorf("IP mismatch expected %q, actual: %q", am.targetIP, addr.Address)
done

2022-05-10 07:07 UTC, kl52752 commented on pkg/loadbalancers/address_manager.go
> +		return fmt.Errorf("address type mismatch expected %q, actual: %q", am.addressType, addr.AddressType)
done

2022-05-10 07:08 UTC, kl52752 commented on pkg/loadbalancers/address_manager.go
> +			return networkTierMismatchError
done

2022-05-10 07:08 UTC, kl52752 commented on pkg/loadbalancers/address_manager.go
> +		return utils.NewNetworkTierErr(resource, am.networkTier.ToGCEValue(), addr.NetworkTier)
done

2022-05-10 07:09 UTC, kl52752 commented on pkg/loadbalancers/l4netlb.go
> +		// User can misconfigure the forwarding rule if Network Tier will not match desired.
done

2022-05-10 07:19 UTC, kl52752 commented on pkg/utils/utils.go
> +}
because `init()` function is call only once when package is first loaded. Changing `var re = regexp.MustCompile` in global scope MustCompalie would be called multiple times (just like it was before).

2022-05-10 07:19 UTC, kl52752 commented on pkg/utils/utils.go
> +// Error function print out Network Tier error.
done

2022-05-10 07:20 UTC, kl52752 commented on pkg/utils/utils.go
> +	// return strings.Contains(netTierError.Error(), NetworkTierMismatchStr)
YES:) done

2022-05-11 00:35 UTC, cezarygerard commented
@bowei ping  we need this PR for RBS launch

2022-05-12 10:55 UTC, kl52752 commented
@bowei all comments are resolved PTAL

2022-05-17 06:56 UTC, bowei reviewed
minor comments

2022-05-17 06:56 UTC, bowei commented on pkg/utils/utils.go
> +var re *regexp.Regexp
we shouldn't call this `re` -- that is too generic to be a variable at package scope.

networkTierErrorRegexp

2022-05-17 06:56 UTC, bowei commented on pkg/utils/utils.go
> +	re = regexp.MustCompile(`The network tier of external IP is STANDARD|PREMIUM, that of Address must be the same.`)
I think you can just do

var (
  networkTierErrorRegexp = regexp.MustCompile...

2022-05-17 12:02 UTC, kl52752 commented on pkg/loadbalancers/address_manager.go
> +		networkTierError := utils.NewNetworkTierErr(resource, string(am.networkTier), string(receivedNetworkTier))
I kind of did, I just need to pass what resource is in error and wha are expected values and there are differen resources like IP address or forwarding rule

2022-05-18 04:02 UTC, bowei commented
/lgtm
/approve

2022-05-18 04:10 UTC, merged