Implement migration from L4 Legacy Target Pool based services to L4 RBS
kubernetes/ingress-gce pull request #1717
Opened 2022-05-19 11:14 UTC by panslava

- Switch target of existing forwarding rule from target pool to regional
  backend service
- Clean up GCP resources used only by legacy service: target pool,
  health checks, firewall rules for health checks

2022-05-19 12:12 UTC, kl52752 requested changes

2022-05-19 12:12 UTC, kl52752 commented on pkg/loadbalancers/forwarding_rules.go
> +			err = composite.SetProxyForForwardingRule(l4netlb.cloud, key, existingFwdRule, bsLink)
So from what I understand this is a place when you wiped out Target field from forwarding rule and set BackendService instead, right?
So my question is if any deletion from `cleanLegacyServiceResources` fails (not becausee of `in used by another resource` reason) then some resources might leaked (since forwarding rule point to BackendService and it is not legacy servicee any more). Is it right?

2022-05-19 12:12 UTC, kl52752 commented on pkg/loadbalancers/forwarding_rules.go
> +			err = l4netlb.cleanLegacyServiceResources()
Is this error going to be exported in metric `L4NetLBsInError`?

2022-05-19 12:16 UTC, panslava commented on pkg/loadbalancers/forwarding_rules.go
> +			err = composite.SetProxyForForwardingRule(l4netlb.cloud, key, existingFwdRule, bsLink)
that is true, if some deletion fails with unexpected error, the resource will be leaked, cause neither ingress-gce nor k/k service-controller will clean it

2022-05-24 16:46 UTC, panslava commented
/hold

2022-05-24 16:48 UTC, closed without merging