Split GetPortsAndProtocol function to 4 separate functions
kubernetes/ingress-gce pull request #1764
Opened 2022-07-29 13:30 UTC by panslava

Return values are independent, and there is no reason to do it in single function

2022-07-29 13:32 UTC, panslava commented
/assign cezarygerard

2022-08-02 17:48 UTC, panslava commented
/assign bowei

2022-08-03 18:34 UTC, cezarygerard commented
small comments, otherwise LGTM

2022-08-03 18:35 UTC, cezarygerard requested changes

2022-08-03 18:35 UTC, cezarygerard commented on pkg/loadbalancers/forwarding_rules.go
> +	ports, protocol := utils.GetPorts(servicePorts), utils.GetProtocol(servicePorts)
please split into 2 lines

2022-08-03 18:35 UTC, cezarygerard commented on pkg/loadbalancers/l4.go
> +	portRanges, protocol := utils.GetServicePortRanges(servicePorts), utils.GetProtocol(servicePorts)
please split into 2 lines

2022-08-03 18:35 UTC, cezarygerard commented on pkg/loadbalancers/l4netlb.go
> +	portRanges, protocol := utils.GetServicePortRanges(servicePorts), utils.GetProtocol(servicePorts)
please split into 2 lines

2022-08-04 12:47 UTC, panslava commented
I also think I should add Unit tests here, cause these functions were not covered

2022-08-12 10:39 UTC, panslava commented on pkg/loadbalancers/forwarding_rules.go
> +	ports, protocol := utils.GetPorts(servicePorts), utils.GetProtocol(servicePorts)
Done

2022-08-12 10:40 UTC, panslava commented on pkg/loadbalancers/l4.go
> +	portRanges, protocol := utils.GetServicePortRanges(servicePorts), utils.GetProtocol(servicePorts)
Done

2022-08-12 10:40 UTC, panslava commented on pkg/loadbalancers/l4netlb.go
> +	portRanges, protocol := utils.GetServicePortRanges(servicePorts), utils.GetProtocol(servicePorts)
Done

2022-08-12 11:49 UTC, cezarygerard reviewed
just readability concerns

again ;-)

2022-08-12 11:49 UTC, cezarygerard commented on pkg/utils/utils_test.go
> +func TestGetPorts(t *testing.T) {
this does not need to be a table test
but I can live with it ;-)

2022-08-12 11:49 UTC, cezarygerard commented on pkg/utils/utils_test.go
> +	testCases := []struct {
this formatting wll read better:

```
testCases := []struct {
		ports         []api_v1.ServicePort
		expectedPorts []string
		desc          string
	}{
		{
			ports:         []api_v1.ServicePort{},
			expectedPorts: []string{},
			desc:          "Empty ports should return empty slice",
		},
		{
			ports: []api_v1.ServicePort{
				{Port: 80}, {Port: 81}, {Port: 3000},
			},
			expectedPorts: []string{"80", "81", "3000"},
			desc:          "Multiple ports",
		},
	}
```

2022-08-12 11:49 UTC, cezarygerard commented on pkg/utils/utils_test.go
> +		{desc: "All Unique", ports: []api_v1.ServicePort{{
this is some weird formatting, try this:

```
		{
			desc: "All Unique",
			ports: []api_v1.ServicePort{
				{Port: 8}, {Port: 66}, {Port: 23}, {Port: 13}, {Port: 89},
			},
			expectedRanges: []string{"8", "13", "23", "66", "89"},
		},
```
Some for other test cases

2022-08-12 11:49 UTC, cezarygerard commented on pkg/utils/utils_test.go
> +func TestGetNodePorts(t *testing.T) {
Check my comments in TestGetPorts
1) this does not need to be a table test
2) inlining some structs in the test case may help readability

2022-08-16 10:15 UTC, panslava commented on pkg/utils/utils_test.go
> +func TestGetPorts(t *testing.T) {
I think there is some value in checking it for "edge" condition (empty slice) and with some real value

2022-08-16 10:15 UTC, panslava commented on pkg/utils/utils_test.go
> +	testCases := []struct {
Fixed

2022-08-16 10:15 UTC, panslava commented on pkg/utils/utils_test.go
> +func TestGetNodePorts(t *testing.T) {
Fixed formatting

2022-08-16 10:15 UTC, panslava commented on pkg/utils/utils_test.go
> +		{desc: "All Unique", ports: []api_v1.ServicePort{{
Fixed

2022-08-16 11:23 UTC, cezarygerard commented on pkg/utils/utils_test.go
> +func TestGetPorts(t *testing.T) {
yeah, I did not notice that the test actually has more than 1 condition.

2022-08-16 11:25 UTC, cezarygerard commented
/lgtm

2022-08-16 11:27 UTC, merged