Cleanup code
kubernetes/ingress-gce pull request #1791
Opened 2022-08-25 16:29 UTC by cezarygerard

Cleanup code:

- get rid of one letter variables named 'L/l/I/|/!/1'
- removed unused parameters from assert func in l4 tests
- split l4//l7 neg endpoint calculators into separate files
- refactor l4 neg calculator

no business logic or test logic has been changed in this commit

2022-08-25 16:37 UTC, cezarygerard commented
/assign panslava

2022-08-26 08:12 UTC, panslava requested changes
Can I ask you to move endpoints refactoring to separate PR? Let's leave here only renaming

2022-08-26 08:12 UTC, panslava commented on pkg/loadbalancers/l4netlb_test.go
> +	l4NetLB.l4HealthChecks = l4ilb.healthChecks
if we change l4healthChecks -> healthChecks on ILB struct should we also change it on NetLB?

2022-08-26 09:09 UTC, cezarygerard commented on pkg/loadbalancers/l4netlb_test.go
> +	l4NetLB.l4HealthChecks = l4ilb.healthChecks
yes, done

2022-08-26 09:10 UTC, cezarygerard commented
@panslava I chave move the neg calculators refactoring to pr/1792

2022-08-26 09:13 UTC, panslava approved these changes

2022-08-26 09:19 UTC, panslava commented
/lgtm

2022-08-26 09:20 UTC, merged