Add a new NetL4LB flag
kubernetes/ingress-gce pull request #1824
Opened 2022-09-21 14:11 UTC by code-elinka

Before this change there was only one
flag "num-l4-workers" to keep a count
of internal and external L4 load
balancer goroutines. It's better to
have 2 separate flags so the new
"num-net-l4-workers" flag was added.

Signed-off-by: Elina Akhmanova <elinka@google.com>

2022-09-22 10:49 UTC, panslava commented
/ok-to-test

2022-09-22 11:33 UTC, panslava requested changes
Thank you, just some small nits, otherwise lgtm

2022-09-22 11:33 UTC, panslava commented on cmd/glbc/main.go
> +		NumNetL4Workers:       flags.F.NumNetL4Workers,
We usually use term "L4NetLB", so let's rename to `NumL4NetLBWorkers"

2022-09-22 11:33 UTC, panslava commented on pkg/flags/flags.go
> +		`Number of parallel internal (ILB) L4 Service worker goroutines.`)
`internal (ILB)` feels repetitive

let's say

`Number of parallel L4 Internal Load Balancer Service worker goroutines.`

2022-09-22 11:33 UTC, panslava commented on pkg/flags/flags.go
> +		`Number of parallel external (XLB/NetLB) L4 Service worker goroutines.`)
Saying both XLB and NetLB is not needed (btw, in this code base, I rarely see term XLB, usually we use NetLB or ELB)

let's say

`Number of parallel L4 External Load Balancer Service worker goroutines.`

2022-09-22 15:55 UTC, code-elinka commented
/ok-to-test

2022-09-22 15:55 UTC, code-elinka commented on cmd/glbc/main.go
> +		NumNetL4Workers:       flags.F.NumNetL4Workers,
Done, thank you

2022-09-22 15:56 UTC, code-elinka commented on pkg/flags/flags.go
> +		`Number of parallel external (XLB/NetLB) L4 Service worker goroutines.`)
Okay, I renamed also the flag itself to `num-l4-net-workers`. I did not add `-lb-` part to keep the flag shorter

2022-09-26 12:07 UTC, code-elinka commented
/unassign prameshj

2022-09-26 12:07 UTC, code-elinka commented
/ok-to-test

2022-09-26 20:09 UTC, code-elinka commented
Tested it locally: 
```
 GLBC=bin/amd64/glbc hack/run-local-glbc.sh --run-l4-netlb-controller --num-l4-net-workers=3 --run-l4-controller
 ```
 Got:  NumL4Workers:5 (default if the flag is not entered),  NumL4NetLBWorkers:3 (from the flag)

2022-09-26 22:12 UTC, panslava approved these changes

2022-09-26 22:12 UTC, panslava commented
/lgtm

2022-09-26 22:14 UTC, merged