Replace GCE Rate Limiter with dynamic throttling strategy for NEG requests
kubernetes/ingress-gce pull request #1892
Opened 2022-12-29 20:22 UTC by alexkats

This change replaces GCE Rate Limiter with dynamic throttling strategy and request group for NEGs.

2022-12-29 20:23 UTC, alexkats commented
/assign @swetharepakula
/cc @swetharepakula
/cc @alan-kut 
/cc @cezarygerard

2023-01-05 11:56 UTC, cezarygerard commented
/ok-to-test

2023-01-18 10:45 UTC, alan-kut requested changes
I don't fully understand the changes here.

I expected:
- sth like DynamicThrottlingClient 
- DynamicThrottlingStrategy

I found:
- BackoffHandler
- RetryHandler
- Request Groups

2023-01-18 10:45 UTC, alan-kut commented on cmd/glbc/main.go
> +	var cloud negtypes.NetworkEndpointGroupCloud
I see that the argument is named cloud as well and golang likes short variables names but cloud here seems really non describing what it is.

I'd call it gcpClient or negClient.

That said - I'm leaving it to you and owners.

2023-01-18 10:45 UTC, alan-kut commented on pkg/flags/flags.go
> +	flag.BoolVar(&F.EnableNegDynamicThrottling, "enable-neg-dynamic-throttling", false, "Enable dynamic throttling strategy for NEG GCE API calls, should be used together with --enable-neg-request-group
I'd call those flags:
- enable dynamic throttling to change the throttler to dynamic throttling
- dynamic throttling strategy to pick strategy

I don't like "Request group" name and I don't think anyone who is not familiar with the design would understand or have intuition what it is

2023-01-18 10:45 UTC, alan-kut commented on pkg/neg/backoff/backoff.go
>  	NextRetryDelay() (time.Duration, error)
NextRequestDelay?

2023-01-18 10:45 UTC, alan-kut commented on pkg/neg/backoff/backoff.go
> +type BackoffHandler interface {
What is the purpose of BackoffHandler?

I don't see a big reason why this can't be a part of the Throttling Strategy.

2023-01-18 10:45 UTC, alan-kut commented on pkg/neg/backoff/backoff.go
>  	// NextRetryDelay returns the delay for next retry or error if maximum number of retries exceeded.
Why there is a maximum number of retries for a backoff handler for a throttling strategy?

2023-01-18 10:45 UTC, alan-kut commented on pkg/neg/backoff/backoff.go
> +type TwoWayBackoffHandler interface {
Can we have one interface? Decrease may be no-op if not needed.

2023-01-18 10:45 UTC, alan-kut commented on pkg/neg/backoff/retry_handler.go
> +// RetryHandler encapsulates logic that handles retry
Why do you introduced retries handler for throttler?

2023-01-18 19:46 UTC, alexkats commented on pkg/flags/flags.go
> +	flag.BoolVar(&F.EnableNegDynamicThrottling, "enable-neg-dynamic-throttling", false, "Enable dynamic throttling strategy for NEG GCE API calls, should be used together with --enable-neg-request-group
I'll rename it to something different for external usage, thanks

2023-01-18 19:48 UTC, alexkats commented on pkg/neg/backoff/backoff.go
> +type BackoffHandler interface {
It's just was moved to another package, it's used for calculating delays for later retries in other places.

2023-01-18 19:49 UTC, alexkats commented on pkg/neg/backoff/backoff.go
>  	// NextRetryDelay returns the delay for next retry or error if maximum number of retries exceeded.
It's something that is used in other places, for strategies this number is set to 0 internally (infinite retries)

2023-01-18 19:50 UTC, alexkats commented on pkg/neg/backoff/backoff.go
> +type TwoWayBackoffHandler interface {
Yes, I think it makes sense, I'll add DecreaseDelay to the base interface

2023-01-18 19:50 UTC, alexkats commented on pkg/neg/backoff/retry_handler.go
> +// RetryHandler encapsulates logic that handles retry
It was just moved to another package, I didn't change anything here

2023-01-18 19:51 UTC, alexkats commented on pkg/neg/backoff/backoff.go
>  	NextRetryDelay() (time.Duration, error)
I'll change it to NextDelay and ResetRetryDelay to ResetDelay

2023-01-18 19:57 UTC, alexkats commented
> I don't fully understand the changes here.
> 
> I expected:
> 
> sth like DynamicThrottlingClient
> DynamicThrottlingStrategy
> I found:
> 
> BackoffHandler
> RetryHandler
> Request Groups

Well, BackoffHandler and RetryHandler are something that was beforehand, I just added an ability to decrease delay for BackoffHandler.

I have `strategy.go` inside `throttling` package and I have request group inside the same package, and I don't know a better name. Probably I can make it just `client.go`, so it will be just `throttling.Client` for callers. But I'm not sure it's better. 

cc: @swetharepakula

2023-01-20 15:52 UTC, alexkats commented on pkg/flags/flags.go
> +	flag.BoolVar(&F.EnableNegDynamicThrottling, "enable-neg-dynamic-throttling", false, "Enable dynamic throttling strategy for NEG GCE API calls, should be used together with --enable-neg-request-group
Tried to find a better naming a description, but feel free to make it even better :)

2023-01-28 02:01 UTC, swetharepakula reviewed
Made a first pass. If possible can you break this change into smaller commits? I am think possibly 3 commits:
1. All the helper function changes
2. The pulling out of the backoff handler into its own package
3. All the proposed changes for dynamic throttling.

This would allow us differentiate the changes and make it easier to review.

Thanks!

2023-01-31 18:47 UTC, alexkats commented on pkg/flags/flags.go
> +		GCENegRateLimit                  RateLimitSpecs
Removed this flag at all

2023-01-31 18:48 UTC, alexkats commented on pkg/flags/flags.go
> +	flag.Var(&F.GCENegRateLimit, "gce-neg-ratelimit",
Yes, that was exactly my thought at the time, but I forgot to remove this flag, thanks for pointing out

2023-01-31 18:49 UTC, alexkats commented on pkg/utils/slice/slice.go
>  package slice
Done

2023-01-31 18:50 UTC, alexkats commented on pkg/neg/backoff/backoff.go
> +package backoff
Split it.

Regarding the reasoning, here are 2 I have in mind:
1. It's just more common than just syncers
2. To avoid cyclic imports (throttling->syncers->throttling or something similar)

2023-01-31 18:51 UTC, alexkats commented on pkg/neg/backoff/backoff.go
>  }
Was not sure about it at the time, fixed

2023-01-31 18:51 UTC, alexkats commented on pkg/neg/throttling/request_group.go
> +	specs := flags.F.GCENegRateLimit.Values()
Done

2023-01-31 18:51 UTC, alexkats commented on pkg/neg/throttling/request_group.go
> +	}
Moved

2023-01-31 18:51 UTC, alexkats commented on pkg/neg/throttling/request_group.go
> +
I think I removed all unneeded extra lines

2023-01-31 18:51 UTC, alexkats commented on pkg/neg/types/cloudprovideradapter.go
> +	if flags.F.EnableNegDynamicThrottlingStrategy {
Done

2023-01-31 18:51 UTC, alexkats commented on pkg/ratelimit/ratelimit.go
> +	if flags.F.EnableNegThrottling && !flags.F.EnableNegDynamicThrottlingStrategy && key.Service == "NetworkEndpointGroups" && strings.HasSuffix(key.Operation, "NetworkEndpoints") {
Done

2023-01-31 18:55 UTC, alexkats commented on pkg/flags/flags.go
> +		EnableNegDynamicThrottlingStrategy bool
Well, currently there are no strategies at all. The idea behind was to:
1) Enable strategies at all and use QPS strategy, which imitates current behavior.
2) Then replace QPS strategy with the dynamic one

Regarding flags, it's possible to have just one with the strategy, but it won't be that obvious IMO. When there's only one flag, if you have this flag set, you'll enable throttling with some strategy, and if the flag is not specified at all, then current behavior is present.

2023-01-31 18:55 UTC, alexkats commented
Thanks for the first round @swetharepakula , I think I addressed all the comments.

2023-02-01 12:36 UTC, alexkats commented
/cc @bowei

2023-02-01 12:37 UTC, alexkats commented
/cc @swetharepakula 
/cc @bowei

2023-02-02 20:03 UTC, swetharepakula commented on pkg/neg/backoff/backoff.go
> +package backoff
Thanks! that makes sense.

2023-02-04 01:14 UTC, bowei commented
Is this PR still to be reviewed or we should review the smaller PRs?

2023-02-04 02:16 UTC, swetharepakula commented on pkg/flags/flags.go
> +		EnableNegDynamicThrottlingStrategy bool
Is the idea to be able to choose the throttling strategy with the flag? If that is the case I think a single flag makes sense. Currently it feels like we are adding a flag per strategy, which I think it is difficult. Is it possible to make this an enum/string that takes in a strategy?

The presence of the flag both enables the throttling and the strategy.

2023-02-09 11:08 UTC, alexkats commented on pkg/flags/flags.go
> +		EnableNegDynamicThrottlingStrategy bool
Removed the flags from this PR, will determine the best approach and create another PR with flags for these changes.

2023-02-09 11:11 UTC, alexkats commented
@bowei This is now the only PR that should be reviewed. I dissected it to 3 commits as @swetharepakula suggested. The first 2 commits are generally some helpers. The last one introduces strategies. There will be another PR with flags to allow a proper rollout of these changes.

2023-05-11 19:09 UTC, closed without merging