improve L4FailedHealthCheckCount metric
kubernetes/ingress-gce pull request #1955
Opened 2023-02-15 09:58 UTC by cezarygerard

do no report multiple times the same case of late sync

2023-02-15 09:59 UTC, cezarygerard commented
/assign @panslava

2023-02-15 09:59 UTC, cezarygerard commented
/assign @code-elinka

2023-02-15 12:38 UTC, panslava requested changes

2023-02-15 12:38 UTC, panslava commented on pkg/l4lb/l4netlbcontroller.go
> +		msg := fmt.Sprintf("L4 ILB Sync happened at time %v, last enqueue time %v- %v after enqueue time, threshold is %v", lastSyncTime, lastEnqueueTime, lastSyncTime.Sub(lastEnqueueTime), enqueueToSyncDe
NetLB

2023-02-15 12:38 UTC, panslava commented on pkg/l4lb/l4netlbcontroller.go
> +		metrics.PublishL4FailedHealthCheckCount(l4ILBControllerName)
l4NetLBControllerName

2023-02-15 12:38 UTC, panslava commented on pkg/l4lb/l4controller.go
> +		// Reset trackers. Otherwise, if there is nothing in the queue then it will report the FailedHealthCheckCount every time the checkHealth is called
now it sounds like -- empty queue will result in errors (just by being empty)

But actually, it means that, if last sync was too long, and nothing happened after that -- it will continue reporting errors

maybe we can rephrase?

2023-02-15 14:16 UTC, cezarygerard commented on pkg/l4lb/l4netlbcontroller.go
> +		msg := fmt.Sprintf("L4 ILB Sync happened at time %v, last enqueue time %v- %v after enqueue time, threshold is %v", lastSyncTime, lastEnqueueTime, lastSyncTime.Sub(lastEnqueueTime), enqueueToSyncDe
copied copied copied....

2023-02-15 14:16 UTC, cezarygerard commented on pkg/l4lb/l4controller.go
> +		// Reset trackers. Otherwise, if there is nothing in the queue then it will report the FailedHealthCheckCount every time the checkHealth is called
copied copied copied....

2023-02-15 14:24 UTC, panslava commented on pkg/l4lb/l4controller.go
> +		msg := fmt.Sprintf("L4 ILB Sync happened at time %v, last enqueue time %v- %v after enqueue time, threshold is %v", lastSyncTime, lastEnqueueTime, lastSyncTime.Sub(lastEnqueueTime), enqueueToSyncDe
sorry for nit, can you bring back the space after %v?

2023-02-15 14:24 UTC, panslava commented on pkg/l4lb/l4netlbcontroller.go
> +		msg := fmt.Sprintf("L4 NetLB Sync happened at time %v, last enqueue time %v- %v after enqueue time, threshold is %v", lastSyncTime, lastEnqueueTime, lastSyncTime.Sub(lastEnqueueTime), enqueueToSync
sorry for nit, can you bring back the space after %v?

2023-02-15 14:32 UTC, panslava commented on pkg/l4lb/l4controller.go
> +		msg := fmt.Sprintf("L4 ILB Sync happened at time %v, last enqueue time %v- %v after enqueue time, threshold is %v", lastSyncTime, lastEnqueueTime, lastSyncTime.Sub(lastEnqueueTime), enqueueToSyncDe
oh also it now reads a bit strange "last enqueue time %v- %v after enqueue time", because "after enqueue time" is about "sync happened after enqueue time"

maybe in this way would be better

```
msg := fmt.Sprintf("L4 ILB Sync happened at time %v, %v after enqueue time, last enqueue time %v, threshold is %v", lastSyncTime,, lastSyncTime.Sub(lastEnqueueTime), lastEnqueueTime, enqueueToSyncDelayThreshold)
```

2023-02-15 14:33 UTC, panslava commented on pkg/l4lb/l4netlbcontroller.go
> +		msg := fmt.Sprintf("L4 NetLB Sync happened at time %v, last enqueue time %v- %v after enqueue time, threshold is %v", lastSyncTime, lastEnqueueTime, lastSyncTime.Sub(lastEnqueueTime), enqueueToSync
Same as for ilb

maybe in this way would be better

`
msg := fmt.Sprintf("L4 NetLB Sync happened at time %v, %v after enqueue time, last enqueue time %v, threshold is %v", lastSyncTime,, lastSyncTime.Sub(lastEnqueueTime), lastEnqueueTime, enqueueToSyncDelayThreshold)
`

2023-02-16 20:05 UTC, panslava commented
/lgtm

2023-02-17 12:44 UTC, panslava commented
/lgtm

2023-02-17 12:50 UTC, merged