Fix firewalls for L4 ILBs.
kubernetes/ingress-gce pull request #2163
Opened 2023-06-07 10:33 UTC by mmamczur

There was an omission in the code for multinet and some firewall rules were created in the incorrect VPC.

2023-06-07 10:57 UTC, code-elinka commented
/ok-to-test

2023-06-09 16:52 UTC, panslava requested changes

2023-06-09 16:52 UTC, panslava commented on pkg/loadbalancers/l4netlb.go
> +	defaultNetwork := network.DefaultNetwork(l4netlb.cloud)
I think it should be not default, but also as done in L4, we should store network in l4netlb struct, and pass it here

Otherwise, I guess it will fail, if nodes are not in default network

(same for l4netlbipv6)

2023-06-09 18:09 UTC, mmamczur commented
I'll store this in l4netlb later when I do multinet for netlb.

Default here means cluster network.
This change will mimic the behavior we had before

On Fri, Jun 9, 2023, 6:53 PM Viacheslav Panasovets ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In pkg/loadbalancers/l4netlb.go
> <https://github.com/kubernetes/ingress-gce/pull/2163#discussion_r1224542987>
> :
>
> > @@ -266,6 +266,7 @@ func (l4netlb *L4NetLB) ensureIPv4NodesFirewall(nodeNames []string, ipAddress st
>  	}
>
>  	// Add firewall rule for L4 External LoadBalancer traffic to nodes
> +	defaultNetwork := network.DefaultNetwork(l4netlb.cloud)
>
> I think it should be not default, but also as done in L4, we should store
> network in l4netlb struct, and pass it here
>
> Otherwise, I guess it will fail, if nodes are not in default network
>
> (same for l4netlbipv6)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/ingress-gce/pull/2163#pullrequestreview-1472650739>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVNNTWHAONYXTCIZLPIUW53XKNIHLANCNFSM6AAAAAAY5VEOVE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-09 18:12 UTC, panslava commented
oh okay, thought default is "default" network in google cloud

thanks for the fix

/lgtm

but let's track, if that will be safe

2023-06-09 18:14 UTC, merged