Change logic of L4 Strong Session Affinity
kubernetes/ingress-gce pull request #2211
Opened 2023-07-28 15:24 UTC by code-elinka

Session Affinity Tracking Policy shouldn't
be updated if the flag for it wasn't set.

2023-07-28 23:40 UTC, aojea commented on pkg/loadbalancers/l4netlb.go
> +	if !l4netlb.enableStrongSessionAffinity || !annotations.HasStrongSessionAffinityAnnotation(l4netlb.Service) {
this may have an unit test covering the regression

2023-08-01 12:21 UTC, code-elinka commented on pkg/loadbalancers/l4netlb.go
> +	if !l4netlb.enableStrongSessionAffinity || !annotations.HasStrongSessionAffinityAnnotation(l4netlb.Service) {
Sure, thank you.

2023-08-01 12:24 UTC, code-elinka commented
/assign @aojea @panslava

2023-08-04 06:09 UTC, panslava requested changes

2023-08-04 06:09 UTC, panslava commented on pkg/backends/backends_test.go
> +func TestBackendSvcEqual(t *testing.T) {
Sorry, I am usually not a fun of being picky about tests, but as I am substituting Cezary....

I don't think we should have this way of storing old/new in map[string]string

I think there are 2 ways to do it better:

1. Just store oldBackendService newBackendService as structs in testCases
2. You could define those backend services even before testsCases in variables. So it will be:
```

	backendService :=  &composite.BackendService{
		Description:         "description",
		LoadBalancingScheme: "EXTERNAL",
		Protocol:            "TCP",
		SessionAffinity:     "CLIENT_IP",
	}
	backendServiceDesc2 := &composite.BackendService{
		Description:         "different-description",
		LoadBalancingScheme: "EXTERNAL",
		Protocol:            "TCP",
		SessionAffinity:     "CLIENT_IP",
	}
	for _, tc := range []struct {
		desc              string
		oldBackendService *composite.BackendService
		newBackendService *composite.BackendService
                 wantEqual bool
	}{
		{
			desc:              "Test with equal services",
			oldBackendService: backendService,
			newBackendService: backendService,
		},
		{
			desc:              "Test with changed description",
			oldBackendService: backendService,
			newBackendService: backendServiceDesc2,
		},
	},
```

2023-08-04 06:09 UTC, panslava commented on pkg/backends/backends_test.go
> +		backendsEqual              bool
use `wantEqual`

2023-08-04 06:09 UTC, panslava commented on pkg/loadbalancers/l4netlb.go
>  // connectionTrackingPolicy returns BackendServiceConnectionTrafficPolicy
typo: returns BackendServiceConnection*Tracking*Policy

2023-08-04 06:09 UTC, panslava commented on pkg/loadbalancers/l4netlb.go
> +	connectionTrackingPolicy.IdleTimeoutSec = int64(*l4netlb.Service.Spec.SessionAffinityConfig.ClientIP.TimeoutSeconds)
Could it happen this will be nil?

2023-08-04 06:09 UTC, panslava commented on pkg/utils/utils.go
> +		EqualStringSets(a.NullFields, b.NullFields)
Are you sure we need to compare ForceSendFields and NullFields? I personally don't know, and not sure, just never saw this in our code

2023-08-04 06:09 UTC, panslava commented on pkg/utils/utils_test.go
> +func TestEqualConnectionTrackingPolicy(t *testing.T) {
The same comments as in EqualBackends

2023-08-07 12:46 UTC, code-elinka commented
/assign @cezarygerard

2023-08-07 16:18 UTC, mmamczur commented on pkg/utils/utils.go
> +		EqualStringSets(a.NullFields, b.NullFields)
ForceSendFields and NullFields are not really parto of BackendService but rather something that structs generated from protos have. You use them to indicate that you want to send an empty value for a field even if it's not set in a patch request etc.
I think we should not compare them

2023-08-08 12:53 UTC, code-elinka commented on pkg/utils/utils.go
> +		EqualStringSets(a.NullFields, b.NullFields)
Please check now :)

2023-08-08 12:55 UTC, code-elinka commented on pkg/utils/utils.go
> +// and return false if at least one parameter is different
I moved it but left both tests. Tell me if you insist on removing the test of helper function.

2023-08-09 09:56 UTC, cezarygerard commented on pkg/backends/backends.go
>  	DefaultConnectionDrainingTimeoutSeconds = 30
are these used outside of this package?
if not then please rename to lower case

	DefaultConnectionDrainingTimeoutSeconds
	PerSessionTrackingMode

2023-08-09 09:56 UTC, cezarygerard commented on pkg/backends/backends_test.go
> +				NullFields:           []string{"abc"},
please remove this test case

it's confusing ihmo

2023-08-09 09:56 UTC, cezarygerard commented on pkg/backends/backends_test.go
> +		},
please remove this test case

it's confusing ihmo

2023-08-09 09:56 UTC, cezarygerard commented on pkg/backends/backends_test.go
> +			desc: "Connection Persistence update",
desc: "ConnectionPersistenceOnUnhealthyBackends uodated by customer"

2023-08-09 09:56 UTC, cezarygerard commented on pkg/backends/backends_test.go
> +				ConnectionPersistenceOnUnhealthyBackends: "DEFAULT_FOR_PROTOCOL",
put "non-default" into oldConnectionTrackingPolicy and DEFAULT_FOR_PROTOCOL in the newConnectionTrackingPolicy

2023-08-09 12:12 UTC, code-elinka commented on pkg/backends/backends.go
>  	DefaultConnectionDrainingTimeoutSeconds = 30
I reused them into l4netlb.go + l4lb_test.go. Do you want to have something unique for those places and change these things to private?

2023-08-09 12:32 UTC, code-elinka commented on pkg/backends/backends_test.go
> +			desc: "Connection Persistence update",
changed a little. is it better?

2023-08-09 13:59 UTC, cezarygerard commented on pkg/backends/backends_test.go
> +func TestConnectionTrackingPolicyEqual(t *testing.T) {
please drop this test and move test cases to TestBackendSvcEqual if they are not present yet

2023-08-09 13:59 UTC, cezarygerard commented on pkg/backends/backends_test.go
> +			},
IMHO it is better not to repeat the same fields between oldBackendService and newBackendService

only initialize fields that differ for readability sake
e.g.

```
		{
			desc: "Test with changed idle timeout",
			oldBackendService: &composite.BackendService{
				ConnectionTrackingPolicy: &composite.BackendServiceConnectionTrackingPolicy{
					IdleTimeoutSec: prolongedIdleTimeout,
				},
			},
			newBackendService: &composite.BackendService{
				ConnectionTrackingPolicy: &composite.BackendServiceConnectionTrackingPolicy{
					IdleTimeoutSec: defaultIdleTimeout,
				},
			},
			wantEqual: false,
		},
		
```

you can also add one more test case 
```
		{
			desc:              "Test empty backedns are equal",
			oldBackendService: &composite.BackendService{},
			newBackendService: &composite.BackendService{},
			wantEqual:         true,
		},
```

to also test the null safety

2023-08-10 09:11 UTC, cezarygerard commented on pkg/backends/backends_test.go
> +func TestBackendSvcEqual(t *testing.T) {
this test does not assert on
- TrackingMode
- Network
- HealthChecks

2023-08-10 12:51 UTC, code-elinka commented on pkg/backends/backends_test.go
> +func TestBackendSvcEqual(t *testing.T) {
done

2023-08-10 12:56 UTC, cezarygerard commented
/lgtm

2023-08-10 13:17 UTC, merged