Try to repurpose dual stack metrics into generic L4 metrics. POC
kubernetes/ingress-gce pull request #2223
Opened 2023-08-08 13:18 UTC by mmamczur

2023-08-09 13:06 UTC, cezarygerard commented on pkg/metrics/l4_metrics.go
> +func (im *ControllerMetrics) computeL4ILBDualStackMetrics() map[L4DualStackServiceLabels]int {
you don't need this anymore

export uses Inc() func

2023-08-09 13:06 UTC, cezarygerard commented on pkg/metrics/l4_metrics.go
> +func (im *ControllerMetrics) computeL4NetLBDualStackMetrics() map[L4DualStackServiceLabels]int {
you don't need this anymore

export uses Inc() func

2023-08-10 00:10 UTC, panslava reviewed
Thanks, Yep! I like it much more!

I have one suggestion, though, as always opinionated. Do you think it would be even more clear, if we split this big l4_metrics.go file (and tests) into 2 (3) files 

l4_metrics
l4_legacy_metrics
(maybe l4_dualstack_metrics)

Maybe that's just me, who like smaller files. I think, it could be easier to navigate inside them, and their functionality should be independent I think? And we will not need to think about legacy metrics when adding something new. Also, one small eyesore for now, is hanging l4_dualstack_metrics_test file, which does not have expected l4_dualstack_metrics anymore, but if we split by files -- it will have it's relative back!

Also, I stopped nitpicking comments at some point, because it is still Draft PR, but double check comments/logs after core functionallity is finished, because I see typos/leftovers saying "dualstack" for new l4 general metrics

2023-08-10 00:10 UTC, panslava commented on pkg/metrics/l4_metrics.go
> +		}).Inc()
.Inc() is probably the biggest question to me

I see that before we were always using pattern:
1. Have a map[serviceName] -> features
2. Have a function "calculateL4NetLB(dualstack-for-example)" that using step-1 map, aggregates counts and returns map[features]counts
3. We iterate through the step-2 map and export those counts to prometheus

With this PR it removes step 2, and we basically get to the real count number by incrementing in a loop

Do you think it is better? I am just not sure, feels like performance can suffer, but also, could it be more error prone? And harder to test? I see you had to change tests, because you don't have "compute" function anymore

2023-08-10 07:04 UTC, mmamczur commented on pkg/metrics/l4_metrics.go
> +	l4ILBs = prometheus.NewGaugeVec(
done

2023-08-10 07:09 UTC, mmamczur commented on pkg/metrics/l4_metrics.go
> +		}).Inc()
yes it's a big change. It's something Cezary came up with to simplify. I think there shouldn't be a performance issue but who knows.

However, if we stick to the compute then export the L4State type falls apart.
To do the compute 'old' style you need some struct with all labels of the metric. for example for DualStack it's (IPFamily, IPFamilyPolicy, Status)
If we keep the L4State like so:
```
type L4ServiceState struct {
	L4DualStackServiceLabels
	L4FeaturesServiceLabels
	// Status specifies status of L4 DualStack Service
	Status L4ServiceStatus
	// FirstSyncErrorTime specifies the time timestamp when the service sync ended up with error for the first time.
	FirstSyncErrorTime *time.Time
}
```
then status can't be part of any Labels. So you can't use `L4DualStackServiceLabels` as the struct to compute.

we could remove Labels from L4ServiceState and just have plain values there. We'd have to convert for computation though

2023-08-10 07:10 UTC, mmamczur commented on pkg/metrics/l4_dualstack_metrics_test.go
> +type l4DualStackServiceLabelsWithStatus struct {
you are right, L4ServiceState is good there

2023-08-10 07:10 UTC, mmamczur commented on pkg/metrics/l4_dualstack_metrics_test.go
> +func labels(ipFaimilies, ipFamilyPolicy string, status L4ServiceStatus) l4DualStackServiceLabelsWithStatus {
done

2023-08-10 07:10 UTC, mmamczur commented on pkg/metrics/l4_metrics.go
> +		fmt.Printf("exporting ip_families=%s, ip_family_policy=%s, status=%s\n", state.IPFamilies, state.IPFamilyPolicy, string(state.Status))
removed, thanks for noticing

2023-08-10 07:10 UTC, mmamczur commented on pkg/metrics/l4_metrics.go
> +// SetL4ILBServiceForLegacyMetric implements L4ILBMetricsCollector.
done

2023-08-10 07:10 UTC, mmamczur commented on pkg/metrics/l4_metrics.go
>  		klog.Fatalf("Ingress Metrics failed to initialize correctly.")
done

2023-08-10 07:11 UTC, mmamczur commented on pkg/metrics/l4_metrics.go
> +			Name: "l4_ilbs",
added '_count'

2023-08-10 07:11 UTC, mmamczur commented on pkg/metrics/l4_metrics.go
> +	// Legacy metric. It has only one label and so it is not possible to find status of services with specific features.
thanks, I'm not good at forming informative comments

2023-08-10 07:12 UTC, mmamczur commented on pkg/metrics/l4_metrics.go
> +	l4LabelMutlinet = "multinet"
done

2023-08-10 07:12 UTC, mmamczur commented on pkg/metrics/l4_metrics.go
> +	l4ILBLegacyCount = prometheus.NewGaugeVec(
done

2023-08-10 07:46 UTC, mmamczur commented
> 

I've split this now. I still need to add tests for the 'new' metric and maybe hunt for any bad names that could still be left

2023-08-10 11:48 UTC, cezarygerard commented on pkg/metrics/l4_metrics.go
> +		}).Inc()
I bet tip of my fingernail that using .Inc() will be faster than simple golang hash map
- prometheus uses only labels as  to generate the hash value
- prometheus runs its own hashing algorithm optimised for storing time series data

we also save a ton of code by not redoing the prometheus job

2023-08-10 12:17 UTC, cezarygerard commented on pkg/l4lb/l4netlbcontroller.go
> +			lc.ctx.ControllerMetrics.DeleteL4NetLBServiceForLegacyMetric(namespacedName)
We don't need delete for new metrics. We always reset gauges before setting new labels

2023-08-10 12:17 UTC, cezarygerard commented on pkg/l4lb/l4controller.go
> +			l4c.ctx.ControllerMetrics.DeleteL4ILBServiceForLegacyMetric(namespacedName)
no need for DeleteL4ILBService (for new metrics)

2023-08-10 12:45 UTC, cezarygerard commented
LGTM overall

2023-08-10 13:41 UTC, mmamczur commented on pkg/metrics/metrics.go
> +	l4ILBDualStackServiceMap map[string]L4ServiceState
renamed

2023-08-10 13:42 UTC, mmamczur commented on pkg/metrics/l4_metrics.go
> +func (im *ControllerMetrics) computeL4ILBDualStackMetrics() map[L4DualStackServiceLabels]int {
deleted

2023-08-10 13:42 UTC, mmamczur commented on pkg/metrics/l4_metrics.go
> +func (im *ControllerMetrics) computeL4NetLBDualStackMetrics() map[L4DualStackServiceLabels]int {
deleted

2023-08-10 13:43 UTC, mmamczur commented
> LGTM overall

ok so what do we do with this? should we go on with it? we have another PR to deal with

2023-08-10 17:33 UTC, mmamczur commented on pkg/metrics/l4_metrics.go
> +// DeleteL4ILBServiceForLegacyMetric implements L4ILBMetricsCollector.
done

2023-08-10 17:43 UTC, panslava commented on pkg/metrics/l4_metrics.go
> +		}).Inc()
Oh, I see what you mean about type problems... yeh makes sense

2023-08-10 19:02 UTC, mmamczur commented
Do we merge then or change more?

On Thu, Aug 10, 2023, 7:43 PM Viacheslav Panasovets <
***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In pkg/metrics/l4_metrics.go
> <https://github.com/kubernetes/ingress-gce/pull/2223#discussion_r1290475760>
> :
>
> > +
> +	klog.V(3).Infof("Exporting L4 ILB DualStack usage metrics")
> +
> +	for key, state := range im.l4ILBServiceMap {
> +		klog.V(6).Infof("ILB Service %s has IPFamilies: %v, IPFamilyPolicy: %t, Status: %v", key, state.IPFamilies, state.IPFamilyPolicy, state.Status)
> +		if state.Status == StatusError &&
> +			state.FirstSyncErrorTime != nil &&
> +			time.Since(*state.FirstSyncErrorTime) >= persistentErrorThresholdTime {
> +			state.Status = StatusPersistentError
> +		}
> +		fmt.Printf("exporting ip_families=%s, ip_family_policy=%s, status=%s\n", state.IPFamilies, state.IPFamilyPolicy, string(state.Status))
> +		l4ILBDualStackCount.With(prometheus.Labels{
> +			"ip_families":      state.IPFamilies,
> +			"ip_family_policy": state.IPFamilyPolicy,
> +			"status":           string(state.Status),
> +		}).Inc()
>
> Oh, I see what you mean about type problems... yeh makes sense
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/ingress-gce/pull/2223#discussion_r1290475760>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVNNTWAERISSYOUJC5RTHVTXUUMTFANCNFSM6AAAAAA3IO7V5E>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-08-10 19:56 UTC, cezarygerard commented
I would like lgtm from @panslava either

2023-08-10 21:20 UTC, panslava commented
Reviewing

2023-08-10 22:21 UTC, panslava requested changes
just some nits, generally good!

2023-08-10 22:21 UTC, panslava commented on pkg/metrics/l4_metrics.go
>  }
nit: feels like we don't need to change the initial object, what do you think if we just do something like

```
func getStatusConsideringPersistentError(state *L4ServiceState) L4ServiceStatus {
	if state.Status == StatusError &&
		state.FirstSyncErrorTime != nil &&
		time.Since(*state.FirstSyncErrorTime) >= persistentErrorThresholdTime {
		return StatusPersistentError
	}
	return state.Status
}
```

and the name is less ambiguous

2023-08-10 22:21 UTC, panslava commented on pkg/metrics/l4_dualstack_metrics.go
>  	}
Use `updateAndGetStatus` (or other name if it will be renamed)

2023-08-10 22:21 UTC, panslava commented on pkg/metrics/l4_dualstack_metrics.go
> +		}).Inc()
Use `updateAndGetStatus` (or other name if it will be renamed)

2023-08-10 22:21 UTC, panslava commented on pkg/metrics/metrics.go
> +	klog.V(3).Infof("Registering L4 ILB usage metrics %v", l4ILBLegacyCount)
l4ILBLegacyCount -> l4ILBCount

2023-08-10 22:21 UTC, panslava commented on pkg/metrics/metrics.go
> +	klog.V(3).Infof("Registering L4 NetLB usage metrics %v", l4ILBLegacyCount)
l4ILBLegacyCount -> l4NetLBCount

2023-08-10 22:21 UTC, panslava commented on pkg/metrics/types.go
> +func InitL4NetLBServiceState(syncTime *time.Time) L4NetLBServiceLegacyState {
I think for consistency better InitL4NetLBServiceState -> InitL4NetLBServiceLegacyState

2023-08-11 06:07 UTC, mmamczur commented on pkg/loadbalancers/l4netlb.go
>  		}
I was even thinking to make this `result` type have a finction so you'd do result.setError(err) and it would know what to do

2023-08-11 06:09 UTC, mmamczur commented on pkg/metrics/l4_metrics.go
> +func InitServiceMetricsState(svc *corev1.Service, startTime *time.Time, isMultinetwork bool) L4ServiceState {
yep it's better, the I just did 'extract' refactor from IDE

2023-08-11 06:13 UTC, mmamczur commented on pkg/metrics/l4_metrics.go
> +// SetL4NetLBService implements L4NetLBMetricsCollector.
hmm this is weird I thought I changed these comments... anyway, updated

2023-08-11 06:20 UTC, mmamczur commented on pkg/metrics/types.go
> +func InitL4NetLBServiceState(syncTime *time.Time) L4NetLBServiceLegacyState {
done

2023-08-11 06:20 UTC, mmamczur commented on pkg/metrics/metrics.go
> +	klog.V(3).Infof("Registering L4 NetLB usage metrics %v", l4ILBLegacyCount)
done

2023-08-11 06:20 UTC, mmamczur commented on pkg/metrics/metrics.go
> +	klog.V(3).Infof("Registering L4 ILB usage metrics %v", l4ILBLegacyCount)
done

2023-08-11 06:21 UTC, mmamczur commented on pkg/metrics/l4_dualstack_metrics.go
> +		}).Inc()
done

2023-08-11 06:21 UTC, mmamczur commented on pkg/metrics/l4_dualstack_metrics.go
>  	}
done

2023-08-11 06:21 UTC, mmamczur commented on pkg/l4lb/l4netlbcontroller.go
> +		klog.V(2).Infof("External L4 Loadbalancer for Service %s ensured, updating its state %v in metrics cache", namespacedName, result.MetricsLegacyState)
added the new one in the log string

2023-08-12 08:13 UTC, mmamczur commented on pkg/metrics/metrics.go
> +	l4NetLBDualStackServiceMap map[string]L4ServiceState
done

2023-08-12 08:13 UTC, mmamczur commented on pkg/metrics/l4_metrics.go
> +// DeleteL4NetLBService implements L4NetLBMetricsCollector.
done

2023-08-12 08:21 UTC, mmamczur commented on pkg/metrics/l4_metrics.go
> +	im.Lock()
done

2023-08-12 08:21 UTC, mmamczur commented on pkg/metrics/l4_metrics.go
>  }
done

2023-08-12 08:22 UTC, mmamczur commented on pkg/metrics/l4_metrics.go
> +	l4NetLBCount.Reset()
done

2023-08-12 20:31 UTC, panslava commented
thank you!
/lgtm
/hold if Cezary wants to give final approval (feel free to unhold if not needed)

2023-08-13 08:33 UTC, mmamczur commented
I'll unhod, Cezary LGTMed this and is away till Wednesday
/unhold

2023-08-13 08:35 UTC, merged