Add and pass enableL7XLBRegional to NEG controller
kubernetes/ingress-gce pull request #2306
Opened 2023-10-26 03:09 UTC by panslava

- No-op change for now
- We will use it later to process negs for gce-regional ingresses

/assign @swetharepakula @spencerhance 
/cc @bowei

2023-11-02 22:51 UTC, spencerhance requested changes

2023-11-02 22:51 UTC, spencerhance commented on pkg/neg/controller.go
> +	enableL7XLBRegional bool
Can we just use the same flag name everywhere?

The controller flag is `EnableIngressRegionalExternal`, but it gets renamed here when you are plumbing it through.  Might as well just use `EnableIngressRegionalExternal` here instead.

2023-11-02 23:19 UTC, panslava commented on pkg/neg/controller.go
> +	enableL7XLBRegional bool
sure, renamed (but keeping private)

2023-11-03 02:13 UTC, spencerhance commented
/lgtm
/approve

2023-11-03 03:00 UTC, merged