Fix port range to port comparison for forwarding rules
kubernetes/ingress-gce pull request #2706
Opened 2024-10-22 21:29 UTC by TheBeeZee

This fixes a bug when an existing forwarding rule lists a distinct a set of ports. If a new port is added to a load balancer that falls within the same range of ports, the forwarding rule will not be updated because we would compare the old and new list of ports as a port range.

For example, with oldPorts = {1, 5, 10} and newPorts = {1, 5, 6, 10}, both old and new ports are converted to port range 1-10 and no change is made to the forwarding rule.

With this change we only convert new ports to a port range if the existing ports are also a port range.

2024-10-23 15:35 UTC, FelipeYepez commented on pkg/loadbalancers/forwarding_rules.go
> +	return existingPortRange == newPortRange
Is there any reason why we are not comparing `utils.EqualStringSets(existingPorts, newPorts)`here?

2024-10-23 15:44 UTC, TheBeeZee commented on pkg/loadbalancers/forwarding_rules.go
> +	return existingPortRange == newPortRange
At this point we are guaranteed that existingPorts is empty (see the check at the top of the function), which means that existing ports are specified as a port range, so we want to compare it as a port range. Remember, we don't want to auto-migrate users from port range to port list, because that would be disruptive to traffic.

If the existing port range covers the same ports as the new ports list, then the forwarding rule will continue working as-is without modifications.

2024-10-23 23:18 UTC, FelipeYepez requested changes
/LGTM

2024-10-23 23:19 UTC, FelipeYepez commented on pkg/loadbalancers/forwarding_rules.go
> +	return existingPortRange == newPortRange
Thanks

2024-10-24 17:32 UTC, TheBeeZee commented on pkg/loadbalancers/forwarding_rules.go
I have added a test case for exactly 5 ports as requested. The ExpectedPorts field is already checked to be empty - the checkForwardingRule() function compares both the port range and ports list.

I have also updated the variable names in Equal() to make it clear which one is the existing and new forwarding rule.

2024-10-24 18:12 UTC, closed without merging